FROM ubuntu:xenial

MAINTAINER Francismar Nascimento da Silva <francislibra@gmail.com>

RUN apt-get update && apt-get install curl wget -qy

RUN wget -qO - "https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub" | apt-key add -

RUN echo "deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main" >> /etc/apt/sources.list.d/saltstack.list

RUN apt-get update & apt-get install python-apt salt-master -qy

RUN echo "interface: 172.21.216.3" >> /etc/salt/master

VOLUME ['/etc/salt/master.d', ]

ADD run.sh /usr/local/bin/run.sh

RUN chmod +x /usr/local/bin/run.sh

RUN rm -rf /var/cache/apk/*

CMD "/usr/local/bin/run.sh"

EXPOSE 4505 4506
